# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  workflow_dispatch:
    inputs:
      executes:
        description: 'Do you want to deploy to prod?'
        required: true
        default: 'false'
#  who-to-greet:  # id of input
#    description: 'Who to greet'
#    required: true
#    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    # - ${{ inputs.who-to-greet }}
    - "World"


